services:
  - type: web
    name: investmap
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATA_DIR
        value: /tmp
    autoDeploy: true
